# Generated by Django 4.1.4 on 2022-12-17 08:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("forum", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="forumpost",
            name="forum",
            field=models.ForeignKey(
                default=1, on_delete=django.db.models.deletion.CASCADE, to="forum.forum"
            ),
            preserve_default=False,
        ),
    ]
