# Generated by Django 4.1.4 on 2022-12-16 23:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("forum", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ForumCategory",
            fields=[
                (
                    "basemodel_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="forum.basemodel",
                    ),
                ),
                ("name", models.CharField(max_length=256, unique=True)),
            ],
            bases=("forum.basemodel",),
        ),
    ]
