# Generated by Django 4.1.4 on 2022-12-16 23:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("forum", "0002_forumcategory"),
    ]

    operations = [
        migrations.AddField(
            model_name="forum",
            name="category",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="forum.forumcategory",
            ),
            preserve_default=False,
        ),
    ]
