# Generated by Django 4.1.4 on 2022-12-17 01:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("forum", "0003_forum_category"),
    ]

    operations = [
        migrations.AlterField(
            model_name="forum",
            name="name",
            field=models.CharField(max_length=256),
        ),
        migrations.AlterUniqueTogether(
            name="forum",
            unique_together={("name", "category")},
        ),
    ]
