# Generated by Django 4.1.4 on 2022-12-17 08:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("forum", "0004_alter_forum_name_alter_forum_unique_together"),
    ]

    operations = [
        migrations.CreateModel(
            name="ForumPost",
            fields=[
                (
                    "basemodel_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="forum.basemodel",
                    ),
                ),
                ("title", models.CharField(max_length=256)),
                ("views", models.IntegerField(default=0)),
                ("content", models.TextField()),
            ],
            bases=("forum.basemodel",),
        ),
    ]
